config/routes.rb
Rails.application.routes.draw do
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :listings do
    resources :bookings, only: %i[index new create]
    resources :missions, only: %i[index new create]
    resources :reservations, only: %i[index new create]
  end
  resources :bookings, except: %i[index new create]
  resources :missions, except: %i[index new create]
  resources :reservations, except: %i[index new create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :listing
end

app/models/listing.rb
class Listing < ApplicationRecord
  has_many :bookings
  has_many :missions
  has_many :reservations
end

app/models/mission.rb
class Mission < ApplicationRecord
  belongs_to :listing
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :listing
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: %i[show edit update destroy]

  def new
    @booking = Booking.new
    @listing = Listing.find(params[:listing_id])
    @booking.listing = @listing
  end

  def create
    @booking = Booking.new(booking_params)
    @listing = Listing.find(params[:listing_id])
    @booking.listing = @listing
    if @booking.save
      redirect_to listing_bookings_path(@listing)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def index
    @bookings = Booking.all
  end

  def show
  end

  def edit
  end

  def update
    if @booking.update(booking_params)
      redirect_to bookings_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @booking.destroy
    @listing = Listing.find(params[:listing_id])
    # @listing = Listing.find(params[:listing_id])
    redirect_to listing_bookings_path(@listing), status: :see_other
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date)
  end

  def set_booking
    @booking = Booking.find(params[:id])
  end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :set_listing, only: %i[show edit update destroy]

  def new
    @listing = Listing.new
  end

  def create
    @listing = Listing.new(listing_params)
    if @listing.save
      redirect_to listings_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def index
    @listings = Listing.all
  end

  def show
  end

  def edit
  end

  def update
    if @listing.update(listing_params)
      redirect_to listings_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @listing.destroy
    redirect_to listings_path, status: :see_other
  end

  private

  def listing_params
    params.require(:listing).permit(:num_room)
  end

  def set_listing
    @listing = Listing.find(params[:id])
  end
end

app/controllers/missions_controller.rb
class MissionsController < ApplicationController
  before_action :set_mission, only: %i[show edit update destroy]

  def new
    @mission = Mission.new
    @listing = Listing.find(params[:listing_id])
    @mission.listing = @listing
  end

  def create
    @mission = Mission.new(mission_params)
    @listing = Listing.find(params[:listing_id])
    @mission.listing = @listing
    if @mission.save
      redirect_to listing_missions_path(@listing)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def index
    @missions = Mission.all
  end

  def show
  end

  def edit
  end

  def update
    @listing = @mission.listing
    if @mission.update(mission_params)
      redirect_to listing_missions_path(@listing)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @mission.destroy
    @listing = Listing.find(params[:listing_id])
    # @listing = Listing.find(params[:listing_id])
    redirect_to listings_path, status: :see_other
  end

  private

  def mission_params
    params.require(:mission).permit(:price, :date, :mission_type)
  end

  def set_mission
    @mission = Mission.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/_form.html.erb
<%= simple_form_for [@listing, @booking] do |f|%>
  <%= f.input :start_date %>
  <%= f.input :end_date %>
  <%= f.submit %>
<% end %>

app/views/bookings/index.html.erb
<h2>Booking Index</h2>
<ul>
  <% @bookings.each do |booking| %>
    <li> Booking ID <%= booking.id %> Start date: <%= booking.start_date.to_date %> End date: <%= booking.end_date.to_date %></li>
    <%= link_to "Delete booking", booking_path(booking), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class:"btn btn-outline-dark"%>
  <% end %>
</ul>

app/views/bookings/new.html.erb
<h3>New booking for Listing number </h3>
<%= render "form" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Challenge</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/listings/_form.html.erb
<%= simple_form_for(@listing) do |f|%>
  <%= f.input :num_room %>
  <%= f.submit %>
<% end %>

app/views/listings/edit.html.erb
<h3>Edit listing number <%= @listing.id %></h3>
<%= render "form" %>

app/views/listings/index.html.erb
<h2>Listing Index</h2>
<ul>
  <% @listings.each do |listing| %>
    <li> Room ID <%= listing.id %>, Number of Rooms <%= listing.num_room %> </li>
  <% end %>
</ul>

app/views/listings/new.html.erb
<h3>New Listing</h3>
<%= render "form" %>

app/views/listings/show.html.erb
<h2>Room number <%= @listing.id %></h2>
<h4>Has <%= @listing.num_room %> rooms</h4>
<%= link_to "Delete this listing", listing_path(@listing), data: {turbo_method: :delete, turbo_confirm: "segurito?"}, class: "btn btn-warning"%>

app/views/missions/_form.html.erb
<%= simple_form_for [@listing, @mission] do |f|%>
  <%= f.input :price %>
  <%= f.input :date %>
  <%= f.input :mission_type %>
  <%= f.submit %>
<% end %>

app/views/missions/edit.html.erb
<h3>Edit mission number <%= @mission.id %></h3>
<%= render "form" %>

app/views/missions/index.html.erb
<h2>Missions Index</h2>
<ul>
  <% @missions.each do |mission| %>
    <li> Mission ID <%= mission.id %>, Price of mission <%= mission.price %>, Type of mission <%= mission.mission_type %>, Date of mission <%= mission.date %></li>
    <%= link_to "Delete this mission", mission_path(mission), data: {turbo_method: :delete, turbo_confirm: "segurito?"}, class: "btn btn-warning"%>
  <% end %>
</ul>

app/views/missions/new.html.erb
<h3>New Mission</h3>
<%= render "form" %>

app/views/missions/show.html.erb
<h2>Mission number <%= @mission.id %></h2>
<h4>Type: <%= @mission.mission_type %></h4>
<h4>Price: <%= @mission.price %></h4>
<h4>Date: <%= @mission.date %></h4>
<%= link_to "Delete this mission", mission_path(@mission), data: {turbo_method: :delete, turbo_confirm: "segurito?"}, class: "btn btn-warning"%>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>